version: 2
updates:
  - package-ecosystem: npm
    directory: /docs-docusaurus
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /src/BuggyBits
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
